DATABASE STR2DATA(char *);
void DATA2STR(char * ,DATABASE );
long long int add_carta(MAO , int , int );
long long int rem_carta(MAO , int , int );
int carta_existe(MAO , int , int );
void distribui(DATABASE * );
int calcula_score(MAO );
int maior_carta_mao(MAO );
int maior_carta_jogada(DATABASE * );
int quem_comeca(DATABASE * );
void separa_val (MAO , int );
void separa_nap (MAO , int );
int teste_straight(int );
int teste_flush(int );
int teste_fullhouse(int );
int teste_fourofakind(int );
int tipo_comb_five(MAO );
void atualizastraight(MAO , int );
void preenchejogada (MAO , int [3]);
int cmpplay (MAO , int );
MAO straightpos (MAO );
MAO flushpos (MAO );
MAO fullhousepos (MAO );
MAO fourofakindpos (MAO );
MAO straightflushpos (MAO );
int joga5 (DATABASE * , int );
void pmjgfourofakind (DATABASE * , int );
void pmjgfullhouse (DATABASE * , int );
void pmjgflush (DATABASE * , int );
void primeira_jogada(DATABASE * , int );
int check_basico(DATABASE * , int );
int check_jogada(DATABASE *, int );
int jogadas_possiveis(DATABASE *, int , int [][5]);
